[env:m5cardputer]
platform = espressif32
board = m5stack-stamps3
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
board_build.partitions = default_16MB.csv

lib_deps = 
    m5stack/M5Cardputer@^1.1.0
    m5stack/M5Unified@^0.2.0
    h2zero/NimBLE-Arduino@^2.0.0
    crankyoldgit/IRremoteESP8266@^2.8.0

build_flags = 
    -DCORE_DEBUG_LEVEL=0
    -DCONFIG_BT_NIMBLE_ROLE_CENTRAL_DISABLED
    -DCONFIG_BT_NIMBLE_ROLE_OBSERVER_DISABLED
